
// This file was autogenerated by PeakRDL-uvm
package aligner_ral_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - ALIGNER::CTRL
    class ALIGNER__CTRL extends uvm_reg;
        rand uvm_reg_field SIZE;
        rand uvm_reg_field OFFSET;
        rand uvm_reg_field CLR;

        function new(string name = "ALIGNER__CTRL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.SIZE = new("SIZE");
            this.SIZE.configure(this, 3, 0, "RW", 0, 'h1, 1, 1, 0);
            this.OFFSET = new("OFFSET");
            this.OFFSET.configure(this, 2, 8, "RW", 0, 'h0, 1, 1, 0);
            this.CLR = new("CLR");
            this.CLR.configure(this, 1, 16, "WO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : ALIGNER__CTRL

    // reg - ALIGNER::STATUS
    class ALIGNER__STATUS extends uvm_reg;
        rand uvm_reg_field CNT_DROP;
        rand uvm_reg_field RX_LVL;
        rand uvm_reg_field TX_LVL;

        function new(string name = "ALIGNER__STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CNT_DROP = new("CNT_DROP");
            this.CNT_DROP.configure(this, 8, 0, "RO", 1, 'h0, 1, 1, 0);
            this.RX_LVL = new("RX_LVL");
            this.RX_LVL.configure(this, 4, 8, "RO", 1, 'h0, 1, 1, 0);
            this.TX_LVL = new("TX_LVL");
            this.TX_LVL.configure(this, 4, 16, "RO", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : ALIGNER__STATUS

    // reg - ALIGNER::IRQEN
    class ALIGNER__IRQEN extends uvm_reg;
        rand uvm_reg_field RX_FIFO_EMPTY;
        rand uvm_reg_field RX_FIFO_FULL;
        rand uvm_reg_field TX_FIFO_EMPTY;
        rand uvm_reg_field TX_FIFO_FULL;
        rand uvm_reg_field MAX_DROP;

        function new(string name = "ALIGNER__IRQEN");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.RX_FIFO_EMPTY = new("RX_FIFO_EMPTY");
            this.RX_FIFO_EMPTY.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.RX_FIFO_FULL = new("RX_FIFO_FULL");
            this.RX_FIFO_FULL.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.TX_FIFO_EMPTY = new("TX_FIFO_EMPTY");
            this.TX_FIFO_EMPTY.configure(this, 1, 2, "RW", 0, 'h0, 1, 1, 0);
            this.TX_FIFO_FULL = new("TX_FIFO_FULL");
            this.TX_FIFO_FULL.configure(this, 1, 3, "RW", 0, 'h0, 1, 1, 0);
            this.MAX_DROP = new("MAX_DROP");
            this.MAX_DROP.configure(this, 1, 4, "RW", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : ALIGNER__IRQEN

    // reg - ALIGNER::IRQ
    class ALIGNER__IRQ extends uvm_reg;
        rand uvm_reg_field RX_FIFO_EMPTY;
        rand uvm_reg_field RX_FIFO_FULL;
        rand uvm_reg_field TX_FIFO_EMPTY;
        rand uvm_reg_field TX_FIFO_FULL;
        rand uvm_reg_field MAX_DROP;

        function new(string name = "ALIGNER__IRQ");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.RX_FIFO_EMPTY = new("RX_FIFO_EMPTY");
            this.RX_FIFO_EMPTY.configure(this, 1, 0, "W1C", 1, 'h0, 1, 1, 0);
            this.RX_FIFO_FULL = new("RX_FIFO_FULL");
            this.RX_FIFO_FULL.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
            this.TX_FIFO_EMPTY = new("TX_FIFO_EMPTY");
            this.TX_FIFO_EMPTY.configure(this, 1, 2, "W1C", 1, 'h0, 1, 1, 0);
            this.TX_FIFO_FULL = new("TX_FIFO_FULL");
            this.TX_FIFO_FULL.configure(this, 1, 3, "W1C", 1, 'h0, 1, 1, 0);
            this.MAX_DROP = new("MAX_DROP");
            this.MAX_DROP.configure(this, 1, 4, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : ALIGNER__IRQ

    // addrmap - ALIGNER
    class ALIGNER extends uvm_reg_block;
        rand ALIGNER__CTRL CTRL;
        rand ALIGNER__STATUS STATUS;
        rand ALIGNER__IRQEN IRQEN;
        rand ALIGNER__IRQ IRQ;

        function new(string name = "ALIGNER");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.CTRL = new("CTRL");
            this.CTRL.configure(this);

            this.CTRL.build();
            this.default_map.add_reg(this.CTRL, 'h0);
            this.STATUS = new("STATUS");
            this.STATUS.configure(this);

            this.STATUS.build();
            this.default_map.add_reg(this.STATUS, 'hc);
            this.IRQEN = new("IRQEN");
            this.IRQEN.configure(this);

            this.IRQEN.build();
            this.default_map.add_reg(this.IRQEN, 'hf0);
            this.IRQ = new("IRQ");
            this.IRQ.configure(this);

            this.IRQ.build();
            this.default_map.add_reg(this.IRQ, 'hf4);
        endfunction : build
    endclass : ALIGNER

endpackage: aligner_ral_pkg
